baseURL: "https://hugo-profile.netlify.app"
languageCode: "en-us"
title: "David Chassagnaud"
theme: hugo-profile

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"
    
Paginate: 3
disqusShortname: gurusabarish
enableRobotsTXT: true

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - identifier: Galerie
      name: Galerie
      title: Blog posts
      url: /gallery
      weight: 1
    - identifier: Analyses R
      name: ◇ Analyses R
      title: Analyses R
      url: /Analyses R
      weight: 2
    - identifier: Publications
      name: ◇ Publications
      title: Publications
      url: /Publications
      weight: 3

    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "David Chassagnaud"
  description: Text about my cool site
  # staticPath: ""  # The path to serve the static files from
  #favicon: "/fav.png"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    disableThemeToggle: false
    defaultTheme: "light" # dark

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    brandName: "David Chassagnaud" # Brand name for the brand | default is the title variable
    disableSearch: true
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: false
      disableAchievements: false
      disableContact: false
      disableCV: false
  # Hero
  hero:
    enable: true
    intro: ""
    title: "David"
    subtitle: "Chassagnaud"
    content: "Page personnelle"
    image: /images/IMG_2387.jpeg
    #button:
    #enable: true
    #name: "Resume"
    #url: "#"
    #download: true
    newPage: true
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/davidchassagnaud/
        - icon: fa fa-envelope
          url: mailto:davidchassagnaud@gmail.com
        - icon: fab fa-github
          url: https://github.com/DavidChnd
        - icon: fab fa-orcid
          url: "https://orcid.org/my-orcid?orcid=0000-0001-7996-8732

      #customIcons:
       # - icon: fa-regular fa-envelope"
        #  url: "david.chassagnaud@gmail.com"  

  # About
  about:
    enable: true
    title: "A propos"
    image: "/images/logo.info.png"
    content: |-
      Ayant suivi une formation en physiologie (animale et végétale) puis en écologie, j'éprouve un fort intéret dans l'étude et la compréhension des processus biologiques. 
      
      Il m'est donc utile d'utiliser et de maitriser des outils qui me permettent de traiter et de synthétiser des données. 

      Je traivail actuellement dans le domaine de l'écophysiologie et plus précisement je participe au projet de recherche Sycomor.
    skills:
      enable: true
      title: "Domaine de compétence : "
      items:
        - "Ecologie"
        - "Physiologie"
        - "GitHub"
        - "R"
        - "Rmarkdown"
        - "ggplot2"


# Expérience
  experience:
    enable: true
    title: "Scolarité"
    items:
      - job: "Université d'Orléans"
        company: "Master Agrosciences -  Parcours Biologie Intégrative et Changements Globaux"
        companyUrl: "https://www.univ-orleans.fr/upload/public/2022-02/Master_Agrosciences_Environnement,%20Territoires_Paysage,%20Forêt_BICG_2022_VD.pdf"
        date: "2019- 2021"
        info:
          enable: false
        featuredLink:
          enable: false
          url: ""
        content: |
          Ce master m'a permit d'acquérir des compétences dans le domaine ...
          
          - Biologie des population
          - Statistiques
          
      - job: "Université Limoges"
        company: "Licence Sciences de la Vie et de la Santé - Parcours Biologie Cellulaire et Physiologie"
        companyUrl: "https://www.sciences.unilim.fr/sciences-de-la-vie-et-de-la-terre/biologie-cellulaire-et-physiologie/"
        date: "2015 - 2019"
        info:
          enable: false
        featuredLink:
          enable: false
          url: ""
        content: |
          Cette formation ma permit d'acquerir de solides bases en biologie et plus particulièrement en physiologie animale végétale.

          - Biologie moléculaire
          - Génétique

      - job: "Lycée August Renoir - Limoges"
        company: "Baccalauréat Scientifique"
        companyUrl: ""
        info:
          enable: false
        date: "2015"
        featuredLink:
          enable: false
          url: ""
        content: |
          Option Sciences de la Vie et de la Terre
          
  # Education
  education:
    enable: true
    title: "Expérience"
    index: false
    items:
      - title: "Ingénieur d'études"
        school:
          name: "Laboratoire de Biologie des Ligneux et des Grandes Cultures"
          url: "https://www.univ-orleans.fr/fr/lblgc"
        date: "CDD : Jan 2022 - Déc 2023"
        Lieu : "Orléans - France"
        content: |
          Je travail actuellement au Laboratoire de Biologie des Ligneux et des Grandes Cultures au sein de l'équipe [Arbres et Réponses aux Contraintes Hydriques et Environnementales - ARCHE](https://www.univ-orleans.fr/fr/lblgc/equipes/arbres-et-reponses-aux-contraintes-hydriques-et-environnementales) en tant qu'ingénieur d'études dans le cadre tu projet de recherche Sycomore. 

          - Test de provenance
          - Pin
          
          Activities annexes : 
          
          - Suivi d'une expérimentation en conditions de sécheresse.
          - Formation au Li-6400 / Li-6800 
        featuredLink:
          enable: false
          url: "https://example.com"

      - title: "Assistant Ingénieur"
        school:
          name: "Laboratoire de Biologie des Ligneux et des Grandes Cultures"
          url: "https://www.univ-orleans.fr/fr/lblgc"
        date: "CDD : Sept - Déc 2022"
        Lieu : "Orléans - France"
        content: |
          Dans le cadre du projet de recherche Presto j'ai mené des expérimentations...
          
          - Spectrométrie infrarouge
          - Modèles de prédiction

        featuredLink:
          enable: false
          name: "Mon poster"
          url: "https://example.com"
          
      - title: "Stage Master 2"
        school:
          name: "Laboratoire d'Ecologie Fonctionelle et Environnement"
          url: "https://www.eco.omp.eu"
        date: "Janvier - Juillet 2021"
        Lieu : " Toulouse - France"
        content: |
          Mon sujet de stage portait sur l'étude Xerolycosa nemoralis comme potentiel bio-indicateur de la pollution héritée à proximité d’une ancienne mine d’Argent dans les Pyrénées françaises.
          
          Les différents objectifs étaitent de déterminer les concentrations de contaminants potentiels : dans le sol, la végétation et les araignées. Évaluer d’éventuelles différences dans les niveaux de contamination entre les sexes et le stade de développement. Enfin, étudier une différence potentielle dans l’accumulation des contaminants au cours de la saison (printemps, début d’été, fin d’été-automne).


          - Ecotoxycologie
          - Bio-indicateur
          
        featuredLink:
          enable: true
          name: Accéder à mon rapport de M2
          url: "https://drive.google.com/file/d/1TSPJ6HhPOYBKU6M9E4pdZpFqlmUtFs9A/view?usp=sharing"
          
      - title: "Stage Master 1"
        school:
          name: "Centre de recherche sur la cognition animale - CNRS"
          url: "https://crca.cbi-toulouse.fr"
        date: "Janvier - Mars 2020"
        Lieu : "Toulouse - France"
        content: |
          Étude comportementale de Physarum polycephalum (« Blob »).
          
          Objectif : Évaluer la prise de décision chez le blob dans différents contextes.
          
          - Ethologie
          - Blob
        featuredLink:
          enable: true
          name: Accéder à mon poster de M1
          url: "https://drive.google.com/file/d/14nUH-PPJON6Z8J8r2HEWdC9SjgvbESuI/view?usp=sharing"






  # projects
  projects:
    enable: true
    title: "Projets"
    items:
      - title: Sycomore
        content: Ce projet...
        image: /images/projects/tout-savoir-sur-la-foret.jpg
        featured:
          name: Voir en détail
          link: https://arche-quickconnect.fr3.quickconnect.to/?launchApp=SYNO.SDS.PDFViewer.Application&SynoToken=22s9A86kj8nok&launchParam=path%3D%252FDavid%2520Chassagnaud%252FIE%252FARD_SyCoMore_Dossier_complet.pdf
        badges:
          - "Ecophysiologie"
          - "Test de provenance"
          - "Pin"
        #links:
          #- icon: fa fa-envelope
           # url: mailto:?subject=Hugo%20Profile%20Template&body=Check%20it%20out:%20https%3a%2f%2fhugo-profile.netlify.app%2fblog%2fmarkdown-syntax%2f
          #- icon: fab fa-github
           # url: https://github.com/gurusabarish/hugo-profile
          #- icon: fab fa-twitter
           # url: https://twitter.com/intent/tweet?text=Check+it+out:&url=https%3A%2F%2Fgithub.com%2Fgurusabarish%2Fhugo-profile

      - title: Presto
        content: 
          Dans un context de changements globaux où l'augmentation de l'intensité et de la fréquence des stress mettent en danger de nombreux organismes, la pérennité des plantes ligneuses implique une meilleure compréhension de leur vulnérabilité et de leur capacité adaptative. L'accès à une caractérisation haut-débit de la réponse des plantes ligneuses à ces stress est donc un enjeu majeur. Au travers de ce projet, sera étudié le potentiel de la  spectrométrie proche infra-rouge pour estimer des caractères complexes liés à la réponse des arbres et de la vigne à des stress. La spectrométrie proche infra-rouge est une méthode d'analyse rapide qui présente l'intérêt d'augmenter l'effort d'échantillonnage pour des traits complexes à mesurer mais aussi de permettre la prédiction de la réponse à un stress avant l'expression des symptômes. L'éventail des stress des stress étudiés dans le projet couvre principalement la vulnérabilité aux stress hydriques et aux bio-agresseurs. Le projet ambitionne d'être à l'initiative d'un outil opérationnel pour les programmes d'amélioration des plantes ligneuses, la gestion des écosystèmes (forestiers, alluviaux) et la viticulture.
        image: /images/projects/converter.jpg
        featured:
          name: Voir en détail
          link: ARD_SyCoMore_Dossier_complet.html
        badges:
          - "NIRS"
          - "Prédiction"
        #links:
         # - icon: fab fa-github
          #  url: https://github.com/gurusabarish/converter
          
    title: "Projets"
    items:
      - title: Sycomore
        content: Ce projet...
        image: /images/projects/tout-savoir-sur-la-foret.jpg
        featured:
          name: Voir en détail
          link: https://arche-quickconnect.fr3.quickconnect.to/?launchApp=SYNO.SDS.PDFViewer.Application&SynoToken=22s9A86kj8nok&launchParam=path%3D%252FDavid%2520Chassagnaud%252FIE%252FARD_SyCoMore_Dossier_complet.pdf
        badges:
          - "Ecophysiologie"
          - "Test de provenance"
          - "Pin"
        #links:
          #- icon: fa fa-envelope
           # url: mailto:?subject=Hugo%20Profile%20Temp
          
    # achivements
  achivements:
    enable: true
    title: "Réalisations"
    items:
      - title: Sycomore
        content: Ce projet...
        image: /images/projects/tout-savoir-sur-la-foret.jpg
        featured:
          name: Voir en détail
          link: https://arche-quickconnect.fr3.quickconnect.to/?launchApp=SYNO.SDS.PDFViewer.Application&SynoToken=22s9A86kj8nok&launchParam=path%3D%252FDavid%2520Chassagnaud%252FIE%252FARD_SyCoMore_Dossier_complet.pdf
        badges:
          - "Ecophysiologie"
          - "Test de provenance"
          - "Pin"
        #links:
          #- icon: fa fa-envelope
           # url: mailto:?subject=Hugo%20Profile%20Template&body=Check%20it%20out:%20https%3a%2f%2fhugo-profile.netlify.app%2fblog%2fmarkdown-syntax%2f
          #- icon: fab fa-github
           # url: https://github.com/gurusabarish/hugo-profile
          #- icon: fab fa-twitter
           # url: https://twitter.com/intent/tweet?text=Check+it+out:&url=https%3A%2F%2Fgithub.com%2Fgurusabarish%2Fhugo-profile


  #Contact
  contact:
    enable: true
    title: "Contact"
    content: |
    
      Laboratoire de Biologie des Ligneux et des Grandes Cultures (LBLGC)
      Université d’Orléans - INRAE USC 1328
      Rue de Chartres - Orléans 45067  
    email: david.chassagnaud@gmail.com
    btnName: "Contactez moi par mail"

  footer:
    recentPosts:
      path: "blogs"
      count: 3
      title: Recent Posts
      enable: false # permet de ne pas inclure la présentation des récents posts
      disableFeaturedImage: false
    socialNetworks:
      github: https://github.com/DavidChnd
      linkedin: https://www.linkedin.com/in/davidchassagnaud/
      orcid: https://orcid.org/my-orcid?orcid=0000-0001-7996-8732

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false
