baseURL: "https://hugo-profile.netlify.app"
languageCode: "en-us"
title: "David Chassagnaud"
theme: hugo-profile

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"
    
Paginate: 3
disqusShortname: gurusabarish
enableRobotsTXT: true

markup:
  goldmark:
    renderer:
      unsafe: true

#Menus:
#  main:
#    - identifier: CV
#      name: Galerie
#      title: Blog posts
#      url: /gallery
#      weight: 1
#    - identifier: Analyses R
#      name: ☰ Analyses R
#      title: ☰  Analyses R
#      url: /Analyses R
#      weight: 2
#    - identifier: Publications
#      name: ☰  Publications
#      title: Publications
#      url: /Publications
#      weight: 3

    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "David Chassagnaud"
  description: Text about my cool site
  # staticPath: ""  # The path to serve the static files from
  #favicon: "/fav.png"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    disableThemeToggle: false
    defaultTheme: "light" # dark

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    brandName: "David Chassagnaud" # Brand name for the brand | default is the title variable
    disableSearch: true
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: false
      disableAchievements: false
      disableContact: false
      disableCV: false
  # Hero
  hero:
    enable: true
    intro: ""
    title: "David"
    subtitle: "Chassagnaud"
    content: "Page personnelle"
    image: /images/IMG_2387.jpeg
    button:
    enable: true
    name: "Resume"
    url: "#"
    download: true
    newPage: true
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/davidchassagnaud/
        - icon: fa fa-envelope
          url: mailto:davidchassagnaud@gmail.com
        - icon: fab fa-github
          url: https://github.com/DavidChnd
        - icon: fab fa-orcid
          url: https://orcid.org/my-orcid?orcid=0000-0001-7996-8732
        - icon: fa fa-address-card
          url: https://drive.google.com/file/d/1zWfHPYnczwa0HIQdh34IO70zgwNwJSiK/view?usp=sharing         


      #customIcons:
       # - icon: fa-regular fa-envelope"
        #  url: "david.chassagnaud@gmail.com"  

  # About
  about:
    enable: true
    title: "A propos"
    #image: "/images/logo.info.png"
    content: |-
      Ayant suivi une formation en physiologie (animale et végétale) puis en écologie, j'éprouve un fort intéret dans l'étude et la compréhension des processus biologiques. 
      
      Il m'est donc utile d'utiliser et de maitriser des outils qui me permettent de traiter et de synthétiser des données. 

      Je traivaille actuellement dans le domaine de l'écophysiologie et plus précisement je participe au projet de recherche SyCoMor.
    skills:
      enable: true
      title: "Domaine de compétence : "
      items:
        - "Ecologie"
        - "Physiologie"
        - "GitHub"
        - "R"
        - "Rmarkdown"
        - "ggplot2"


# Expérience
  experience:
    enable: true
    title: "Scolarité"
    items:
      - job: "Université d'Orléans"
        company: "• Master Agrosciences - Parcours Biologie Intégrative et Changements Globaux"
        companyUrl: "https://www.univ-orleans.fr/upload/public/2022-02/Master_Agrosciences_Environnement,%20Territoires_Paysage,%20Forêt_BICG_2022_VD.pdf"
        date: "2019- 2021"
        info:
          enable: false
        featuredLink:
          enable: false
          url: ""
        content: |
          Ce master m'a permit d'acquérir des compétences dans le domaine ...
          
          - Biologie des population
          - Statistiques
          
      - job: "Université Limoges"
        company: "• Licence Sciences de la Vie et de la Santé - Parcours Biologie Cellulaire et Physiologie"
        companyUrl: "https://www.sciences.unilim.fr/sciences-de-la-vie-et-de-la-terre/biologie-cellulaire-et-physiologie/"
        date: "2015 - 2019"
        info:
          enable: false
        featuredLink:
          enable: false
          url: ""
        content: |
          Cette formation ma permit d'acquerir de solides bases en biologie et plus particulièrement en physiologie animale végétale.

          - Biologie moléculaire
          - Génétique

      - job: "Lycée August Renoir - Limoges"
        company: "• Baccalauréat Scientifique"
        companyUrl: ""
        info:
          enable: false
        date: "2015"
        featuredLink:
          enable: false
          url: ""
        content: |
          Option Sciences de la Vie et de la Terre
          
  # Education
  education:
    enable: true
    title: "Expérience"
    index: false
    items:
      - title: "Ingénieur d'études"
        school:
          name: "Laboratoire de Biologie des Ligneux et des Grandes Cultures"
          url: "https://www.univ-orleans.fr/fr/lblgc"
        date: "Jan 22 - Déc 2023"
        Lieu : "Orléans - France"
        content: |
          Je travail actuellement au Laboratoire de Biologie des Ligneux et des Grandes Cultures au sein de l'équipe [Arbres et Réponses aux Contraintes Hydriques et Environnementales - ARCHE](https://www.univ-orleans.fr/fr/lblgc/equipes/arbres-et-reponses-aux-contraintes-hydriques-et-environnementales) en tant qu'ingénieur d'études dans le cadre tu projet de recherche Sycomore. 

          - Test de provenance
          - Pin
          
          Activities annexes : 
          
          - Suivi d'une expérimentation en conditions de sécheresse.
          - Formation au Li-6400 / Li-6800 
        featuredLink:
          enable: true
          name: "En savoir + sur le projet SyCoMore"
          url: "https://drive.google.com/file/d/1aYGbBbT7qYZgC0rrfLH1UeUtqda8Rved/view?usp=sharing"

      - title: "Assistant Ingénieur"
        school:
          name: "Laboratoire de Biologie des Ligneux et des Grandes Cultures"
          url: "https://www.univ-orleans.fr/fr/lblgc"
        date: "Sept - Déc 2022"
        Lieu : "Orléans - France"
        content: |
          Dans le cadre du projet de recherche Presto j'ai mené des expérimentations...
          
          - Spectrométrie infrarouge
          - Modèles de prédiction

        featuredLink:
          enable: false
          name: ""
          url: "https://example.com"
          
      - title: "Stage Master 2"
        school:
          name: "Laboratoire d'Ecologie Fonctionelle et Environnement"
          url: "https://www.eco.omp.eu"
        date: "Janvier - Juillet 2021"
        Lieu : " Toulouse - France"
        content: |
          Mon sujet de stage portait sur l'étude Xerolycosa nemoralis comme potentiel bio-indicateur de la pollution héritée à proximité d’une ancienne mine d’Argent dans les Pyrénées françaises.
          
          Les différents objectifs étaitent de déterminer les concentrations de contaminants potentiels : dans le sol, la végétation et les araignées. Évaluer d’éventuelles différences dans les niveaux de contamination entre les sexes et le stade de développement. Enfin, étudier une différence potentielle dans l’accumulation des contaminants au cours de la saison (printemps, début d’été, fin d’été-automne).


          - Ecotoxycologie
          - Bio-indicateur
          
        featuredLink:
          enable: true
          name: Accéder à mon rapport de M2
          url: "https://cvws.icloud-content.com/B/AeqMMsaF6Bd_qXC4Yokln4G4qIQaAQCOgK7k5i-IZ1Jtqaic-lbZf8R8/Rapport+final+M2+David+Chassagnaud.pdf?o=ApwM1dAmimjDfKhYmPqnhApV-22UY5KjwAMr3MyX8dNy&v=1&x=3&a=CAogHkOS9xZ9TdXXt3l-G4B0Ry1KMtXCSiXbd1Cvr1nuKOkSaxDLkd-u2TAYy-66sNkwIgEAUgS4qIQaWgTZf8R8aiXX_gE31QdAYzS36k-74Y1IrDLPRmhQT7Q7xSsIxJYA9pgrs82xciVgBCFNPhddKub4vFPtMcVqJOZk6rHZyNFA3Wplj8RNKHWN1o1V&e=1673259824&fl=&r=ff06a329-f660-4783-845a-e13ff7ce8375-1&k=G8S2FOInaGCEyC8vVsI1uA&ckc=com.apple.clouddocs&ckz=com.apple.CloudDocs&p=39&s=_2pNkxMHQKF1Na4OQCEhaPVhVUM&cd=i"
          
      - title: "Stage Master 1"
        school:
          name: "Centre de recherche sur la cognition animale - CNRS"
          url: "https://crca.cbi-toulouse.fr"
        date: "Janvier - Mars 2020"
        Lieu : "Toulouse - France"
        content: |
          Étude comportementale de Physarum polycephalum (« Blob »).
          
          Objectif : Évaluer la prise de décision chez le blob dans différents contextes.
          
          - Ethologie
          - Blob
        featuredLink:
          enable: true
          name: Accéder à mon poster de M1
          url: "https://cvws.icloud-content.com/B/AS1unW27olNe6OVGqfAtq8OQtXSjAb_c3v6FPUmjsNaPczC7uAP12S4v/Poster+final+M1+David+Chassagnaud.pdf?o=AqHAdwNJ52mLMjzkHK8dZ7yJtL9GhIYxgF9wffOGCf-B&v=1&x=3&a=CAogKJHZPFyIibydSVYJ_D0c0uugCwYNAwpBq7zk3hYRcQsSaxCPx5uv2TAYj6T3sNkwIgEAUgSQtXSjWgT12S4vaiUQNoCpaVRdVNxhfp822uVm4wPnXyFcTLYINXkmH-oohwQPXvVSciX89VW29ZPk37HLUqgqDzNfPP4F56uHu7EW69M8LzIc7RNfYf6m&e=1673260814&fl=&r=9b51facc-80a9-4f72-a3bf-fedb926ff060-1&k=xLPZx-JNjvmKV5EMybS7qw&ckc=com.apple.clouddocs&ckz=com.apple.CloudDocs&p=39&s=giM5FzbfX8svZDxPMGPQDJXv6wk&cd=i"


  # projects
  projects:
    enable: true
    title: "Publications"
    items:
      - title: 
        content: 
        image: /images/projects/publi1.png
        featured:
          name: Accéder à l'article
          link: https://www.sciencedirect.com/science/article/abs/pii/S0098847222003951
        badges:
          - "Ecophysiologie"
          - "Test de provenance"
          - "Pin"
        #links:
          #- icon: fa fa-envelope
           # url: mailto:?subject=Hugo%20Profile%20Template&body=Check%20it%20out:%20https%3a%2f%2fhugo-profile.netlify.app%2fblog%2fmarkdown-syntax%2f
          #- icon: fab fa-github
           # url: https://github.com/gurusabarish/hugo-profile
          #- icon: fab fa-twitter
           # url: https://twitter.com/intent/tweet?text=Check+it+out:&url=https%3A%2F%2Fgithub.com%2Fgurusabarish%2Fhugo-profile


    title: "Publications"
    items:
      - title: 
        content: 
        image: /images/projects/publi1.png
        featured:
          name: Accéder à l'article
          link: https://www.sciencedirect.com/science/article/abs/pii/S0098847222003951
        badges:
          - "Xylem hydraulic failure"
          - "Nitrogen"
          - "Non-structural carbohydrates"
          - "Populus"
          - "Tree death"
          - "Water deficit"
        #links:
          #- icon: fa fa-github
           # url: https://github.com/gurusabarish/converter
          

    # achivements
  achivements:
    enable: true
    title: "Curriculum vitæ"
    items:
      - title:
        content:
        image: /images/projects/cv.png
        featured:
          name: Visualiser mon CV
          link: https://drive.google.com/file/d/1zWfHPYnczwa0HIQdh34IO70zgwNwJSiK/view?usp=sharing
        #badges:
         # - "Ecophysiologie"
          #- "Test de provenance"
          #- "Pin"
        #links:
          #- icon: fa fa-envelope
           # url: mailto:?subject=Hugo%20Profile%20Template&body=Check%20it%20out:%20https%3a%2f%2fhugo-profile.netlify.app%2fblog%2fmarkdown-syntax%2f
          #- icon: fab fa-github
           # url: https://github.com/gurusabarish/hugo-profile
          #- icon: fab fa-twitter
           # url: https://twitter.com/intent/tweet?text=Check+it+out:&url=https%3A%2F%2Fgithub.com%2Fgurusabarish%2Fhugo-profile



  #Contact
  contact:
    enable: true
    title: "Contact"
    content: |
    
      Laboratoire de Biologie des Ligneux et des Grandes Cultures (LBLGC)
      Université d’Orléans - INRAE USC 1328
      Rue de Chartres - Orléans 45067  
    email: david.chassagnaud@gmail.com
    btnName: "Contactez moi par mail"

  footer:
    recentPosts:
      path: "blogs"
      count: 3
      title: Recent Posts
      enable: false # permet de ne pas inclure la présentation des récents posts
      disableFeaturedImage: false
    socialNetworks:
      github: https://github.com/DavidChnd
      linkedin: https://www.linkedin.com/in/davidchassagnaud/
      orcid: https://orcid.org/my-orcid?orcid=0000-0001-7996-8732

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false
